# Generated by Django 4.1.2 on 2022-11-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_literal_literal'),
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('mostrarEnPedigree', models.BooleanField(verbose_name='Mostrar En Pedigree')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='loperro',
            options={'ordering': ['descripcion'], 'verbose_name': 'Libro Origenes Perro', 'verbose_name_plural': 'Libro Origenes Perros'},
        ),
        migrations.AlterModelOptions(
            name='zbresultado',
            options={'ordering': ['abreviatura'], 'verbose_name': 'ZB Resultado', 'verbose_name_plural': 'ZB Resultados'},
        ),
        migrations.RemoveField(
            model_name='perro',
            name='criador1',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='criador2',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='edPedigree',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='fechaTitular1',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='fechaTitular2',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='hdPedigree',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='korungPedigree',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='titular1',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='titular2',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='zbPedigree',
        ),
        migrations.AlterField(
            model_name='perro',
            name='lo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LO_Perro_set', to='perros.loperro', verbose_name='Libro Origenes'),
        ),
        migrations.CreateModel(
            name='PruebaPerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.SmallIntegerField(default=0, verbose_name='Nivel')),
                ('fechaPrueba', models.DateTimeField(verbose_name='Fecha Prueba')),
                ('perro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Perro_PruebaPerro_set', to='perros.perro', verbose_name='Perro')),
                ('prueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Prueba_PruebaPerro_set', to='perros.prueba', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Prueba Perro',
                'verbose_name_plural': 'Pruebas Perros',
                'ordering': ['fechaPrueba'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Estado Perro',
                'verbose_name_plural': 'Estados Perros',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='perro',
            name='estadoPerro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EstadoPerro_Perro_set', to='perros.estadoperro', verbose_name='Estado Perro'),
        ),
    ]
