# Generated by Django 4.1.2 on 2022-11-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_remove_perro_ad_remove_perro_dph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradoresultado',
            name='literales',
        ),
        migrations.RemoveField(
            model_name='ipresultado',
            name='literales',
        ),
        migrations.RemoveField(
            model_name='phresultado',
            name='literales',
        ),
        migrations.RemoveField(
            model_name='pshresultado',
            name='literales',
        ),
        migrations.RemoveField(
            model_name='rhresultado',
            name='literales',
        ),
        migrations.RemoveField(
            model_name='zhresultado',
            name='literales',
        ),
        migrations.DeleteModel(
            name='FHResultado',
        ),
        migrations.DeleteModel(
            name='GradoResultado',
        ),
        migrations.DeleteModel(
            name='IPResultado',
        ),
        migrations.DeleteModel(
            name='PHResultado',
        ),
        migrations.DeleteModel(
            name='PSHResultado',
        ),
        migrations.DeleteModel(
            name='RHResultado',
        ),
        migrations.DeleteModel(
            name='ZHResultado',
        ),
    ]
