# Generated by Django 4.1.2 on 2023-01-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_remove_gradoresultado_literales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cesionario',
            old_name='perro',
            new_name='perro_cesionario',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='perro',
            new_name='perro_titular',
        ),
    ]
