# Generated by Django 4.1.2 on 2022-10-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoIdioma', models.CharField(max_length=2, unique=True, verbose_name='Código Idioma')),
                ('idioma', models.CharField(max_length=50, unique=True, verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['idioma'],
            },
        ),
        migrations.CreateModel(
            name='Literal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=255, unique=True, verbose_name='Literal')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Idioma_Literal_set', to='general.idioma', verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Literal',
                'verbose_name_plural': 'Literales',
                'ordering': ['literal'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre País')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código país')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Región')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pais_Region_set', to='general.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Provincia')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Region_Provincia_set', to='general.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Forma Pago',
                'verbose_name_plural': 'Formas Pago',
                'ordering': ['descripcion'],
            },
        ),
    ]
