# Generated by Django 4.1.2 on 2022-10-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import perfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('fechaBaja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('baja', models.BooleanField(blank=True, default=False, null=True, verbose_name='Baja')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Afijo',
                'verbose_name_plural': 'Afijos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('codigoPostal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Población')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('baja', models.BooleanField(blank=True, default=False, null=True, verbose_name='Baja')),
                ('fechaBaja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('codigoPostal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Población')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('diasEntrenamiento', models.IntegerField(blank=True, null=True, verbose_name='Días Entrenamiento')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('fechaBaja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('baja', models.BooleanField(blank=True, default=False, null=True, verbose_name='Baja')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Delegacion_GrupoTrabajo_set', to='perfiles.delegacion', verbose_name='Delegación')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
                ('monitorInstructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MonitorInstructor_GrupoTrabajo_set', to=settings.AUTH_USER_MODEL, verbose_name='Monitor/Instructor')),
            ],
            options={
                'verbose_name': 'Grupo Trabajo',
                'verbose_name_plural': 'Grupos Trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Motivo Baja Usuario',
                'verbose_name_plural': 'Motivos Baja Usuario',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Tipo Socio',
                'verbose_name_plural': 'Tipos Socios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=perfiles.models.custom_upload_to, verbose_name='Avatar')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='DNI')),
                ('numeroSocio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número socio')),
                ('fechaNacimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('codigoPostal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Población')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('criador', models.BooleanField(blank=True, null=True, verbose_name='Criador')),
                ('figurante', models.BooleanField(blank=True, null=True, verbose_name='Figurante')),
                ('trazador', models.BooleanField(blank=True, null=True, verbose_name='Trazador')),
                ('juez', models.BooleanField(blank=True, null=True, verbose_name='Juez')),
                ('inspector', models.BooleanField(blank=True, null=True, verbose_name='Inspector')),
                ('faltaPago', models.BooleanField(blank=True, null=True, verbose_name='Falta Pago')),
                ('cuentaBancaria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cuenta Bancaria')),
                ('fechaAlta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('fechaBaja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('baja', models.BooleanField(blank=True, default=False, null=True, verbose_name='Baja')),
                ('afijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Afijo_Perfil_set', to='perfiles.afijo', verbose_name='Afijo')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Delegacion_Perfil_set', to='perfiles.delegacion', verbose_name='Delegación')),
                ('grupoTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoTrabajo_Perfil_set', to='perfiles.grupotrabajo', verbose_name='Grupo Trabajo')),
                ('motivoBajaUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MotivoBaja_Perfil_set', to='perfiles.motivobajausuario', verbose_name='Motivo Baja Usuario')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pais_Perfil_set', to='general.pais', verbose_name='Pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Provincia_Perfil_set', to='general.provincia', verbose_name='Provincia')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Region_Perfil_set', to='general.region', verbose_name='Región')),
                ('tipoSocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoSocio_Perfil_set', to='perfiles.tiposocio', verbose_name='Tipo Socio')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tratamiento_Perfil_set', to='general.tratamiento', verbose_name='Tratamiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Perfil_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBajaGrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Motivo Baja Grupo Trabajo',
                'verbose_name_plural': 'Motivos Baja Grupo Trabajo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBajaDelegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Motivo Baja Delegación',
                'verbose_name_plural': 'Motivos Baja Delegaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBajaAfijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('literales', models.ManyToManyField(to='general.literal', verbose_name='Literales')),
            ],
            options={
                'verbose_name': 'Motivo Baja Afijo',
                'verbose_name_plural': 'Motivos Baja Afijo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='motivoBajaGrupoTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MotivoBaja_GrupoTrabajo_set', to='perfiles.motivobajagrupotrabajo', verbose_name='Motivo Baja Grupo Trabajo'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pais_GrupoTrabajo_set', to='general.pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Provincia_GrupoTrabajo_set', to='general.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Region_GrupoTrabajo_set', to='general.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='grupotrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Responsable_GrupoTrabajo_set', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='motivoBajaDelegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MotivoBaja_Delegacion_set', to='perfiles.motivobajadelegacion', verbose_name='Motivo Baja Delegacion'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pais_Delegacion_set', to='general.pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Provincia_Delegacion_set', to='general.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Region_Delegacion_set', to='general.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='vocalCria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VocalCria_Delegacion_set', to=settings.AUTH_USER_MODEL, verbose_name='Vocal Cría'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='vocalPresidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VocalPresidente_Delegacion_set', to=settings.AUTH_USER_MODEL, verbose_name='Vocal Presidente'),
        ),
        migrations.AddField(
            model_name='delegacion',
            name='vocalTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VocalTrabajo_Delegacion_set', to=settings.AUTH_USER_MODEL, verbose_name='Vocal Trabajo'),
        ),
        migrations.AddField(
            model_name='afijo',
            name='motivoBajaAfijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MotivoBaja_Afijo_set', to='perfiles.motivobajaafijo', verbose_name='Motivo Baja Afijo'),
        ),
        migrations.AddField(
            model_name='afijo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Propietario_Afijo_set', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
