# Generated by Django 4.1.2 on 2022-11-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afijo',
            name='propietario',
        ),
    ]
